
import { Language, Translation } from './types';

export const PLAN_LIMITS: Record<string, { video: number; image: number; audio: number }> = {
  'Free': { video: 3, image: 10, audio: 5 },
  'Starter': { video: 10, image: 50, audio: 20 },
  'Pro': { video: 40, image: 200, audio: 100 },
  'Enterprise': { video: 9999, image: 9999, audio: 9999 } // Effectively unlimited
};

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.AZ]: {
    heroTitle: 'Sehirbaz AI – Güclü Süni İntellekt Alətləri',
    heroSubtitle: 'Sözlərinizi Həqiqətə Çevirin. Təsvir yazın – AI sizin üçün HD video, realist şəkil və səs klonu yaratsın.',
    ctaButton: 'İndi Yaratmağa Başlayın',
    videoTitle: 'AI ilə Avtomatik Video Yaratma',
    videoDesc: 'Sadəcə bir cümlə ilə peşəkar keyfiyyətli videolar əldə edin.',
    videoFeatures: ['HD Keyfiyyət', '60 FPS dəstək', 'Peşəkar kadr keçidləri', 'Avtomatik rəng korreksiyası'],
    langTitle: 'Çoxdilli Dəstək',
    langDesc: 'Videolarınızı və məzmununuzu Azərbaycan, İngilis, Rus və Gürcü dillərində yaradın.',
    imageTitle: 'Promptla Şəkil Hazırlayın',
    imageDesc: 'İstədiyiniz təsviri yazın və AI dərhal yaratsın.',
    imageFeatures: ['Ultra-realistik şəkillər', '3D, anime, fotorealizm', 'Limit yoxdur'],
    voiceTitle: 'Səs Klonlama',
    voiceDesc: 'Mətninizi təbii və axıcı səsə çevirin.',
    voiceFeatures: ['Real insana bənzər səs', 'Çoxdilli danışıq', 'Emosional ton dəstəyi'],
    demoTitle: 'AI ilə Yaradılan Videolar',
    demoCategories: ['Hamısı', 'Təbiət', 'Şəhər', 'Kreativ', 'Portret', 'Fantastika'],
    demoItemBadge: 'AI ilə yaradılıb',
    demoItemTitle: 'Kinematoqrafik kadr',
    playgroundTitle: 'Öz Videonuzu Yoxlayın',
    playgroundDesc: 'Bir təsvir yazın və AI saniyələr ərzində sizin üçün HD keyfiyyətli video yaratsın.',
    pricingTitle: 'Aylıq Abunə Planları',
    pricingSubtitle: 'Kreativliyinizi üzə çıxarmaq üçün mükəmməl planı seçin.',
    pricingFeatures: ['Limitsiz generasiya', 'İstənilən vaxt ləğv et', 'Premium model çıxışları', '24/7 dəstək'],
    footerCopyright: '© 2025 Sehirbaz AI. Bütün hüquqlar qorunur.',
    navHome: 'Ana Səhifə',
    navPricing: 'Qiymətlər',
    generateBtn: 'Yarat',
    generating: 'Yaradılır...',
    download: 'Yüklə',
    promptPlaceholder: 'Təsvirinizi bura yazın...',
    selectKey: 'Google API Açarı Seçin',
    loginRequired: 'Zəhmət olmasa davam etmək üçün API açarı seçin',
    marketingQuote: 'Bir təsvir yazın və AI saniyələr ərzində sizin üçün HD keyfiyyətli video yaratsın. Təbiət səhnələri, şəhər atmosferi, kreativ animasiyalar və ya öz ideyanız – nə istəsəniz yaradın. İndi sınayın və süni intellektin gücünü hiss edin!',
    planStarter: 'Başlanğıc',
    planPro: 'Pro',
    planEnterprise: 'Korporativ',
    planPopular: 'MƏŞHUR',
    perMonth: '/ay',
    btnChooseStarter: 'Başlanğıc Seç',
    btnGoPro: 'Pro-ya Keç',
    btnContactSales: 'Satışla Əlaqə',
    feat50Images: '50 AI Şəkil/ay',
    feat5MinsVideo: '5 Dəq Video/ay',
    featStandardSpeed: 'Standart Sürət',
    feat30MinsVideo: '30 Dəq Video/ay',
    featVoiceCloning: 'Səs Klonlama',
    featUnlimited: 'Hər şey Limitsiz',
    featPrioritySupport: 'Prioritet Dəstək',
    featApiAccess: 'API Girişi',
    tabVideo: 'Video',
    tabImage: 'Şəkil',
    tabAudio: 'Səs',
    labelPrompt: 'Təsvir',
    labelTts: 'Mətn-Səs',
    labelVoice: 'Səs seçimi',
    btnPreview: 'Səsi Yoxla',
    previewing: 'Oxudulur...',
    errorGeneric: 'Xəta baş verdi. Zəhmət olmasa yenidən cəhd edin.',
    errorRateLimit: 'Limit aşıldı. Zəhmət olmasa bir az gözləyin və yenidən cəhd edin.',
    errorInvalidKey: 'Yanlış API açarı. Zəhmət olmasa düzgün açar seçin.',
    errorContentPolicy: 'Təhlükəsizlik siyasətinə görə bloklandı. Zəhmət olmasa promptu dəyişin.',
    errorNetwork: 'İnternet bağlantısı xətası. Bağlantınızı yoxlayın.',
    heroBadge: 'Sehirbaz AI v2.0',
    browserVideoSupport: 'Brauzeriniz videonu dəstəkləmir.',
    altGenerated: 'AI tərəfindən yaradılmış məzmun',
    altDemo: 'Demo video görüntüsü',
    paymentTitle: 'Sadə Ödəniş',
    paymentDesc: 'Qeydiyyatsız, sürətli ödəniş edin.',
    orderSummary: 'Sifarişin xülasəsi',
    total: 'Cəmi',
    cardName: 'Kart sahibinin adı',
    cardNumber: 'Kart nömrəsi',
    expiry: 'Ay/İl',
    cvc: 'CVC',
    payNow: 'Ödə',
    paymentSuccess: 'Ödəniş Uğurludur!',
    paymentSuccessDesc: 'Balansınız artırıldı!',
    backToHome: 'Ana Səhifəyə Qayıt',
    emailLabel: 'Email ünvanı',
    loginTitle: 'Daxil Ol',
    registerTitle: 'Hesab Yarat',
    authSubtitle: 'Pulsuz AI video yaratmağa başlayın',
    freeTrialBadge: '3 pulsuz video yaradın',
    nameLabel: 'Ad',
    passwordLabel: 'Şifrə',
    confirmPasswordLabel: 'Şifrəni təsdiq edin',
    signInBtn: 'Daxil Ol',
    signUpBtn: 'Hesab yarat',
    haveAccount: 'Artıq hesabınız var?',
    noAccount: 'Hesabınız yoxdur?',
    profileTitle: 'İstifadəçi Profili',
    currentPlan: 'Cari Plan',
    usageStats: 'İstifadə Statistikası',
    imagesGenerated: 'Yaradılmış Şəkillər',
    videosGenerated: 'Yaradılmış Videolar',
    logout: 'Çıxış',
    navLogin: 'Giriş',
    navProfile: 'Profil',
    welcomeBack: 'Xoş gəldin',
    viewAll: 'Hamısına Bax',
    termsText: 'Mən qəbul edirəm İstifadə şərtləri',
    privacyText: 'Mən qəbul edirəm Məxfilik siyasəti',
    authFeatureInstant: 'Ani generasiya',
    authFeatureHD: 'HD keyfiyyət',
    authFeatureSecure: 'Təhlükəsiz və etibarlı',
    usageLimitReached: 'İstifadə limiti doldu',
    usageUpgradeMsg: 'Davam etmək üçün planınızı yeniləyin.',
    usageRemaining: 'Qalan',
    upgradePlan: 'Planı Yenilə',
    tabOverview: 'İcmal',
    tabHistory: 'Tarixçə',
    tabSettings: 'Tənzimləmələr',
    noHistory: 'Hələlik heç bir məzmun yaradılmayıb.',
    saveChanges: 'Yadda saxla',
    settingsSaved: 'Məlumatlar yeniləndi!',
    showMore: 'Daha çox göstər',
    showLess: 'Daha az göstər',
    magicToolTitle: 'AI Kreativ Studiya',
    magicToolDesc: 'Fikirlərinizi reallaşdırmaq üçün generativ alətlər və sürətli əməliyyatlar.',
    genTextToImage: 'Mətndən Görüntü',
    genFill: 'Generativ Dolğu',
    genImageFromScene: 'Səhnədən Görüntü',
    genTextToVector: 'Mətndən Vektor',
    genRecolor: 'Yenidən Rəngləndirmə',
    genTextEffects: 'Mətn Effektləri',
    genTemplate: 'Şablon Yarat',
    genTextToVideo: 'Mətndən Video',
    genImageToVideo: 'Görüntüdən Video',
    genMusic: 'Musiqi Yarat',
    genSoundFx: 'Səs Effektləri',
    genAvatar: 'Mətndən Avatar',
    genTextToSpeech: 'Nitq Yarat',
    genVoiceToSfx: 'Səsdən Effektlər',
    genLogo: 'Logo Yarat',
    qaTitle: 'Sürətli Əməliyyatlar',
    qaRemoveBg: 'Arxa Planı Sil',
    qaCropImage: 'Şəkli Kəs',
    qaMergeVideo: 'Videoları Birləşdir',
    qaSubtitle: 'Alt Yazı Əlavə Et',
    qaQrCode: 'QR Kod Yarat',
    qaCropVideo: 'Videonu Kəs',
    qaResizeVideo: 'Video Ölçüsünü Dəyiş',
    qaTrimVideo: 'Videonu Qısalt',
    qaConvertMp4: 'MP4-ə Çevir',
    qaResizeImage: 'Şəkil Ölçüsünü Dəyiş',
    qaTranslateVideo: 'Videonu Tərcümə Et',
    qaEnhanceSpeech: 'Danışığı Yaxşılaşdır',
    qaTranslateAudio: 'Səsi Tərcümə Et',
    navVideoTools: 'Video Alətləri',
    navImageTools: 'Şəkil Alətləri',
    navAudioTools: 'Səs Alətləri',
    enterAmount: 'Məbləği daxil edin (AZN)',
    creditsReceived: 'Qazanacağınız Kredit',
    topUpBtn: 'Balans Artır',
    quickPayTitle: 'Sürətli Ödəniş',
    betaDisclaimer: 'Diqqət: Bu Beta versiyadır, texniki problemlər ola bilər. Bu səbəbdən üzr istəyirik. Hörmətlə, Sehirbaz AI.'
  },
  [Language.EN]: {
    heroTitle: 'Sehirbaz AI – Powerful AI Tools Platform',
    heroSubtitle: 'Turn Your Words into Reality. Write a description – AI creates HD video, realistic images, and voice clones for you.',
    ctaButton: 'Start Creating Now',
    videoTitle: 'Automated AI Video Generation',
    videoDesc: 'Get professional quality videos with just one sentence.',
    videoFeatures: ['HD Quality', '60 FPS support', 'Professional transitions', 'Auto color correction'],
    langTitle: 'Multi-language Support',
    langDesc: 'Create content in Azerbaijani, English, Russian, and Georgian.',
    imageTitle: 'Generate Images from Prompts',
    imageDesc: 'Write a prompt and AI generates it instantly.',
    imageFeatures: ['Ultra-realistic images', '3D, anime, photorealism', 'No limits'],
    voiceTitle: 'Voice Cloning',
    voiceDesc: 'Convert your text into natural, lifelike speech.',
    voiceFeatures: ['Human-like voice clones', 'Multi-lingual speech', 'Emotional tone support'],
    demoTitle: 'AI Generated Showcase',
    demoCategories: ['All', 'Nature', 'City', 'Creative', 'Portrait', 'Sci-Fi'],
    demoItemBadge: 'Generated by AI',
    demoItemTitle: 'Cinematic shot',
    playgroundTitle: 'Test Your Ideas',
    playgroundDesc: 'Write a description and AI will create an HD quality video for you in seconds.',
    pricingTitle: 'Monthly Subscription Plans',
    pricingSubtitle: 'Choose the perfect plan to unleash your creativity.',
    pricingFeatures: ['Unlimited generation', 'Cancel anytime', 'Premium model outputs', '24/7 support'],
    footerCopyright: '© 2025 Sehirbaz AI. All rights reserved.',
    navHome: 'Home',
    navPricing: 'Pricing',
    generateBtn: 'Generate',
    generating: 'Generating...',
    download: 'Download',
    promptPlaceholder: 'Type your description here...',
    selectKey: 'Select Google API Key',
    loginRequired: 'Please select an API key to continue',
    marketingQuote: 'Write a description and AI will create an HD quality video for you in seconds. Nature scenes, city atmosphere, creative animations or your own idea – create whatever you want. Try it now and feel the power of artificial intelligence!',
    planStarter: 'Starter',
    planPro: 'Pro',
    planEnterprise: 'Enterprise',
    planPopular: 'POPULAR',
    perMonth: '/mo',
    btnChooseStarter: 'Choose Starter',
    btnGoPro: 'Go Pro',
    btnContactSales: 'Contact Sales',
    feat50Images: '50 AI Images/mo',
    feat5MinsVideo: '5 Mins Video/mo',
    featStandardSpeed: 'Standard Speed',
    feat30MinsVideo: '30 Mins Video/mo',
    featVoiceCloning: 'Voice Cloning',
    featUnlimited: 'Unlimited Everything',
    featPrioritySupport: 'Priority Support',
    featApiAccess: 'API Access',
    tabVideo: 'Video',
    tabImage: 'Image',
    tabAudio: 'Voice',
    labelPrompt: 'Prompt',
    labelTts: 'Text to Speech',
    labelVoice: 'Select Voice',
    btnPreview: 'Preview Voice',
    previewing: 'Playing...',
    errorGeneric: 'An error occurred while generating content. Please try again.',
    errorRateLimit: 'Rate limit exceeded. Please wait a moment and try again.',
    errorInvalidKey: 'Invalid API Key. Please select a valid key.',
    errorContentPolicy: 'Content blocked due to safety guidelines. Please modify your prompt.',
    errorNetwork: 'Network error. Please check your connection.',
    heroBadge: 'Sehirbaz AI v2.0',
    browserVideoSupport: 'Your browser does not support video.',
    altGenerated: 'AI generated content',
    altDemo: 'Demo video preview',
    paymentTitle: 'Simple Payment',
    paymentDesc: 'Pay quickly without registration.',
    orderSummary: 'Order Summary',
    total: 'Total',
    cardName: 'Cardholder Name',
    cardNumber: 'Card Number',
    expiry: 'MM/YY',
    cvc: 'CVC',
    payNow: 'Pay',
    paymentSuccess: 'Payment Successful!',
    paymentSuccessDesc: 'Your balance has been topped up!',
    backToHome: 'Back to Home',
    emailLabel: 'Email Address',
    loginTitle: 'Log In',
    registerTitle: 'Create Account',
    authSubtitle: 'Start creating free AI videos',
    freeTrialBadge: 'Create 3 free videos',
    nameLabel: 'Name',
    passwordLabel: 'Password',
    confirmPasswordLabel: 'Confirm Password',
    signInBtn: 'Sign In',
    signUpBtn: 'Create Account',
    haveAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    profileTitle: 'User Profile',
    currentPlan: 'Current Plan',
    usageStats: 'Usage Statistics',
    imagesGenerated: 'Images Generated',
    videosGenerated: 'Videos Generated',
    logout: 'Logout',
    navLogin: 'Login',
    navProfile: 'Profile',
    welcomeBack: 'Welcome back',
    viewAll: 'View All',
    termsText: 'I accept the Terms of Use',
    privacyText: 'I accept the Privacy Policy',
    authFeatureInstant: 'Instant generation',
    authFeatureHD: 'HD Quality',
    authFeatureSecure: 'Safe & Secure',
    usageLimitReached: 'Usage limit reached',
    usageUpgradeMsg: 'Upgrade your plan to continue creating.',
    usageRemaining: 'Remaining',
    upgradePlan: 'Upgrade Plan',
    tabOverview: 'Overview',
    tabHistory: 'History',
    tabSettings: 'Settings',
    noHistory: 'No content generated yet.',
    saveChanges: 'Save Changes',
    settingsSaved: 'Details updated successfully!',
    showMore: 'Show More',
    showLess: 'Show Less',
    magicToolTitle: 'AI Creative Studio',
    magicToolDesc: 'Generative tools and quick actions to bring your ideas to life.',
    genTextToImage: 'Text to Image',
    genFill: 'Generative Fill',
    genImageFromScene: 'Image from Scene',
    genTextToVector: 'Text to Vector',
    genRecolor: 'Generative Recolor',
    genTextEffects: 'Text Effects',
    genTemplate: 'Create Template',
    genTextToVideo: 'Text to Video',
    genImageToVideo: 'Image to Video',
    genMusic: 'Generate Music',
    genSoundFx: 'Sound Effects',
    genAvatar: 'Text to Avatar',
    genTextToSpeech: 'Generate Speech',
    genVoiceToSfx: 'Voice to SFX',
    genLogo: 'Create Logo',
    qaTitle: 'Quick Actions',
    qaRemoveBg: 'Remove Background',
    qaCropImage: 'Crop Image',
    qaMergeVideo: 'Merge Videos',
    qaSubtitle: 'Add Subtitles',
    qaQrCode: 'Generate QR Code',
    qaCropVideo: 'Crop Video',
    qaResizeVideo: 'Resize Video',
    qaTrimVideo: 'Trim Video',
    qaConvertMp4: 'Convert to MP4',
    qaResizeImage: 'Resize Image',
    qaTranslateVideo: 'Translate Video',
    qaEnhanceSpeech: 'Enhance Speech',
    qaTranslateAudio: 'Translate Audio',
    navVideoTools: 'Video Tools',
    navImageTools: 'Image Tools',
    navAudioTools: 'Audio Tools',
    enterAmount: 'Enter Amount (AZN)',
    creditsReceived: 'Credits You Receive',
    topUpBtn: 'Top Up',
    quickPayTitle: 'Quick Pay',
    betaDisclaimer: 'Notice: This is a Beta version, technical issues may occur. We apologize for any inconvenience. Regards, Sehirbaz AI.'
  },
  [Language.RU]: {
    heroTitle: 'Sehirbaz AI – Мощная платформа ИИ',
    heroSubtitle: 'Превратите слова в реальность. Опишите – ИИ создаст HD видео, реалистичные изображения и клоны голоса.',
    ctaButton: 'Начать творить',
    videoTitle: 'Автоматическое создание видео',
    videoDesc: 'Получите видео профессионального качества всего за одно предложение.',
    videoFeatures: ['HD Качество', 'Поддержка 60 FPS', 'Профессиональные переходы', 'Автокоррекция цвета'],
    langTitle: 'Многоязычная поддержка',
    langDesc: 'Создавайте контент на азербайджанском, английском, русском и грузинском языках.',
    imageTitle: 'Генерация изображений',
    imageDesc: 'Напишите запрос, и ИИ создаст это мгновенно.',
    imageFeatures: ['Ультра-реалистичные фото', '3D, аниме, концепт-арт', 'Без ограничений'],
    voiceTitle: 'Клонирование голоса',
    voiceDesc: 'Превратите текст в естественную речь.',
    voiceFeatures: ['Реалистичный голос', 'Многоязычная речь', 'Эмоциональные тона'],
    demoTitle: 'Галерея ИИ',
    demoCategories: ['Все', 'Природа', 'Город', 'Креатив', 'Портрет', 'Фантастика'],
    demoItemBadge: 'Создано ИИ',
    demoItemTitle: 'Кинематографичный кадр',
    playgroundTitle: 'Проверьте сами',
    playgroundDesc: 'Напишите описание, и ИИ создаст для вас HD видео за секунды.',
    pricingTitle: 'Тарифные планы',
    pricingSubtitle: 'Выберите идеальный план, чтобы раскрыть свой творческий потенциал.',
    pricingFeatures: ['Безлимитная генерация', 'Отмена в любое время', 'Премиум модели', 'Поддержка 24/7'],
    footerCopyright: '© 2025 Sehirbaz AI. Все права защищены.',
    navHome: 'Главная',
    navPricing: 'Цены',
    generateBtn: 'Создать',
    generating: 'Создание...',
    download: 'Скачать',
    promptPlaceholder: 'Введите ваше описание...',
    selectKey: 'Выбрать API ключ',
    loginRequired: 'Пожалуйста, выберите API ключ для продолжения',
    marketingQuote: 'Напишите описание, и ИИ за считанные секунды создаст для вас видео HD-качества. Сцены природы, городская атмосфера, креативные анимации или ваша собственная идея — создавайте все, что захотите. Попробуйте прямо сейчас и почувствуйте силу искусственного интеллекта!',
    planStarter: 'Стартовый',
    planPro: 'Про',
    planEnterprise: 'Корпоративный',
    planPopular: 'ПОПУЛЯРНЫЙ',
    perMonth: '/мес',
    btnChooseStarter: 'Выбрать Стартовый',
    btnGoPro: 'Перейти на Про',
    btnContactSales: 'Связаться с нами',
    feat50Images: '50 ИИ изображений/мес',
    feat5MinsVideo: '5 мин видео/мес',
    featStandardSpeed: 'Стандартная скорость',
    feat30MinsVideo: '30 мин видео/мес',
    featVoiceCloning: 'Клонирование голоса',
    featUnlimited: 'Всё безлимитно',
    featPrioritySupport: 'Приоритетная поддержка',
    featApiAccess: 'Доступ к API',
    tabVideo: 'Видео',
    tabImage: 'Изображение',
    tabAudio: 'Голос',
    labelPrompt: 'Описание',
    labelTts: 'Текст в речь',
    labelVoice: 'Выбор голоса',
    btnPreview: 'Прослушать',
    previewing: 'Воспроизведение...',
    errorGeneric: 'Произошла ошибка. Пожалуйста, попробуйте еще раз.',
    errorRateLimit: 'Превышен лимит запросов. Пожалуйста, подождите немного.',
    errorInvalidKey: 'Неверный API ключ. Пожалуйста, выберите действительный ключ.',
    errorContentPolicy: 'Контент заблокирован политикой безопасности. Пожалуйста, измените запрос.',
    errorNetwork: 'Ошибка сети. Проверьте подключение.',
    heroBadge: 'Sehirbaz AI v2.0',
    browserVideoSupport: 'Ваш браузер не поддерживает видео.',
    altGenerated: 'Сгенерированный контент',
    altDemo: 'Демонстрация видео',
    paymentTitle: 'Простая оплата',
    paymentDesc: 'Оплатите быстро без регистрации.',
    orderSummary: 'Итог заказа',
    total: 'Всего',
    cardName: 'Имя держателя карты',
    cardNumber: 'Номер карты',
    expiry: 'ММ/ГГ',
    cvc: 'CVC',
    payNow: 'Оплатить',
    paymentSuccess: 'Оплата успешна!',
    paymentSuccessDesc: 'Ваш баланс пополнен!',
    backToHome: 'Вернуться на главную',
    emailLabel: 'Электронная почта',
    loginTitle: 'Войти',
    registerTitle: 'Создать аккаунт',
    authSubtitle: 'Начните создавать бесплатные ИИ видео',
    freeTrialBadge: 'Создайте 3 бесплатных видео',
    nameLabel: 'Имя',
    passwordLabel: 'Пароль',
    confirmPasswordLabel: 'Подтвердите пароль',
    signInBtn: 'Войти',
    signUpBtn: 'Создать аккаунт',
    haveAccount: 'Уже есть аккаунт?',
    noAccount: 'Нет аккаунта?',
    profileTitle: 'Профиль пользователя',
    currentPlan: 'Текущий план',
    usageStats: 'Статистика использования',
    imagesGenerated: 'Создано изображений',
    videosGenerated: 'Создано видео',
    logout: 'Выйти',
    navLogin: 'Войти',
    navProfile: 'Профиль',
    welcomeBack: 'С возвращением',
    viewAll: 'Смотреть все',
    termsText: 'Я принимаю Условия использования',
    privacyText: 'Я принимаю Политику конфиденциальности',
    authFeatureInstant: 'Мгновенная генерация',
    authFeatureHD: 'HD Качество',
    authFeatureSecure: 'Безопасно и надежно',
    usageLimitReached: 'Лимит использования исчерпан',
    usageUpgradeMsg: 'Обновите тариф для продолжения.',
    usageRemaining: 'Осталось',
    upgradePlan: 'Обновить тариф',
    tabOverview: 'Обзор',
    tabHistory: 'История',
    tabSettings: 'Настройки',
    noHistory: 'Контент пока не создан.',
    saveChanges: 'Сохранить',
    settingsSaved: 'Данные успешно обновлены!',
    showMore: 'Показать больше',
    showLess: 'Показать меньше',
    magicToolTitle: 'AI Творческая Студия',
    magicToolDesc: 'Генеративные инструменты и быстрые действия для реализации ваших идей.',
    genTextToImage: 'Текст в Изображение',
    genFill: 'Генеративная Заливка',
    genImageFromScene: 'Сцена в Изображение',
    genTextToVector: 'Текст в Вектор',
    genRecolor: 'Перекрашивание',
    genTextEffects: 'Текстовые Эффекты',
    genTemplate: 'Создать Шаблон',
    genTextToVideo: 'Текст в Видео',
    genImageToVideo: 'Изображение в Видео',
    genMusic: 'Создать Музыку',
    genSoundFx: 'Звуковые Эффекты',
    genAvatar: 'Текст в Аватар',
    genTextToSpeech: 'Текст в Речь',
    genVoiceToSfx: 'Голос в SFX',
    genLogo: 'Создать Логотип',
    qaTitle: 'Быстрые Действия',
    qaRemoveBg: 'Удалить Фон',
    qaCropImage: 'Обрезать Фото',
    qaMergeVideo: 'Объединить Видео',
    qaSubtitle: 'Добавить Субтитры',
    qaQrCode: 'QR Код',
    qaCropVideo: 'Обрезать Видео',
    qaResizeVideo: 'Изменить Размер Видео',
    qaTrimVideo: 'Подрезать Видео',
    qaConvertMp4: 'Конвертировать в MP4',
    qaResizeImage: 'Изменить Размер Фото',
    qaTranslateVideo: 'Перевести Видео',
    qaEnhanceSpeech: 'Улучшить Речь',
    qaTranslateAudio: 'Перевести Аудио',
    navVideoTools: 'Видео Инструменты',
    navImageTools: 'Фото Инструменты',
    navAudioTools: 'Аудио Инструменты',
    enterAmount: 'Введите сумму (AZN)',
    creditsReceived: 'Получите Кредитов',
    topUpBtn: 'Пополнить',
    quickPayTitle: 'Быстрая Оплата',
    betaDisclaimer: 'Внимание: Это бета-версия, возможны технические ошибки. Приносим извинения за неудобства. С уважением, Sehirbaz AI.'
  },
  [Language.GE]: {
    heroTitle: 'Sehirbaz AI – ძლიერი ხელოვნური ინტელექტის პლატფორმა',
    heroSubtitle: 'აქციეთ თქვენი სიტყვები რეალობად. დაწერეთ აღწერა - AI შეგიქმნით HD ვიდეოს, რეალისტურ სურათს და ხმის კლონს.',
    ctaButton: 'დაიწყეთ შექმნა',
    videoTitle: 'AI ვიდეოს გენერაცია',
    videoDesc: 'მიიღეთ პროფესიონალური ხარისხის ვიდეოები მხოლოდ ერთი წინადადებით.',
    videoFeatures: ['HD ხარისხი', '60 FPS მხარდაჭერა', 'პროფესიონალური გადასვლები', 'ფერების ავტომატური კორექცია'],
    langTitle: 'მრავალენოვანი მხარდაჭერა',
    langDesc: 'შექმენით კონტენტი აზერბაიჯანულ, ინგლისურ, რუსულ და ქართულ ენებზე.',
    imageTitle: 'სურათის შექმნა',
    imageDesc: 'დაწერეთ მოთხოვნა და AI მყისიერად შექმნის მას.',
    imageFeatures: ['ულტრა-რეალისტური სურათები', '3D, ანიმე, ფოტორეალიზმი', 'ლიმიტების გარეშე'],
    voiceTitle: 'ხმის კლონირება',
    voiceDesc: 'გადააქციეთ ტექსტი ბუნებრივ მეტყველებად.',
    voiceFeatures: ['ადამიანის მსგავსი ხმა', 'მრავალენოვანი საუბარი', 'ემოციური ტონები'],
    demoTitle: 'AI-ს მიერ შექმნილი ნამუშევრები',
    demoCategories: ['ყველა', 'ბუნება', 'ქალაქი', 'კრეატივი', 'პორტრეტი', 'ფანტასტიკა'],
    demoItemBadge: 'AI-ს მიერ შექმნილი',
    demoItemTitle: 'კინემატოგრაფიული კადრი',
    playgroundTitle: 'შეამოწმეთ თქვენი ვიდეო',
    playgroundDesc: 'დაწერეთ აღწერა და AI შეგიქმნით HD ვიდეოს წამებში.',
    pricingTitle: 'სააბონენტო გეგმები',
    pricingSubtitle: 'აირჩიეთ იდეალური გეგმა თქვენი შემოქმედების გასათავისუფლებლად.',
    pricingFeatures: ['შეუზღუდავი გენერაცია', 'გაუქმება ნებისმიერ დროს', 'პრემიუმ მოდელები', '24/7 მხარდაჭერა'],
    footerCopyright: '© 2025 Sehirbaz AI. ყველა უფლება დაცულია.',
    navHome: 'მთავარი',
    navPricing: 'ფასები',
    generateBtn: 'შექმნა',
    generating: 'იქმნება...',
    download: 'ჩამოტვირთვა',
    promptPlaceholder: 'აკრიფეთ თქვენი აღწერა აქ...',
    selectKey: 'აირჩიეთ API გასაღები',
    loginRequired: 'გთხოვთ აირჩიოთ API გასაღები გასაგრძელებლად',
    marketingQuote: 'დაწერეთ აღწერა და AI შეგიქმნით HD ხარისხის ვიდეოს წამებში. ბუნების სცენები, ქალაქის ატმოსფერო, კრეატიული ანიმაციები ან საკუთარი იდეა - შექმენით რაც გსურთ. სცადეთ ახლა და იგრძენით ხელოვნური ინტელექტის ძალა!',
    planStarter: 'საწყისი',
    planPro: 'პრო',
    planEnterprise: 'კორპორატიული',
    planPopular: 'პოპულარული',
    perMonth: '/თვე',
    btnChooseStarter: 'აირჩიეთ საწყისი',
    btnGoPro: 'გადადით პროზე',
    btnContactSales: 'დაუკავშირდით გაყიდვებს',
    feat50Images: '50 AI სურათი/თვე',
    feat5MinsVideo: '5 წთ ვიდეო/თვე',
    featStandardSpeed: 'სტანდარტული სიჩქარე',
    feat30MinsVideo: '30 წთ ვიდეო/თვე',
    featVoiceCloning: 'ხმის კლონირება',
    featUnlimited: 'შეუზღუდავი ყველაფერი',
    featPrioritySupport: 'პრიორიტეტული მხარდაჭერა',
    featApiAccess: 'API წვდომა',
    tabVideo: 'ვიდეო',
    tabImage: 'სურათი',
    tabAudio: 'ხმა',
    labelPrompt: 'აღწერა',
    labelTts: 'ტექსტი ხმად',
    labelVoice: 'ხმის არჩევა',
    btnPreview: 'ხმის მოსმენა',
    previewing: 'უკრავს...',
    errorGeneric: 'დაფიქსირდა შეცდომა. გთხოვთ სცადოთ თავიდან.',
    errorRateLimit: 'ლიმიტი ამოწურულია. გთხოვთ დაელოდოთ და სცადოთ მოგვიანებით.',
    errorInvalidKey: 'არასწორი API გასაღები. გთხოვთ აირჩიოთ ვალიდური გასაღები.',
    errorContentPolicy: 'შინაარსი დაბლოკილია უსაფრთხოების წესების გამო. გთხოვთ შეცვალოთ მოთხოვნა.',
    errorNetwork: 'ქსელის შეცდომა. გთხოვთ შეამოწმოთ კავშირი.',
    heroBadge: 'Sehirbaz AI v2.0',
    browserVideoSupport: 'თქვენი ბრაუზერი არ უჭერს მხარს ვიდეოს.',
    altGenerated: 'AI-ს მიერ შექმნილი კონტენტი',
    altDemo: 'ვიდეო დემო',
    paymentTitle: 'მარტივი გადახდა',
    paymentDesc: 'გადაიხადეთ სწრაფად რეგისტრაციის გარეშე.',
    orderSummary: 'შეკვეთის შეჯამება',
    total: 'სულ',
    cardName: 'ბარათის მფლობელის სახელი',
    cardNumber: 'ბარათის ნომერი',
    expiry: 'თვე/წელი',
    cvc: 'CVC',
    payNow: 'გადახდა',
    paymentSuccess: 'გადახდა წარმატებულია!',
    paymentSuccessDesc: 'თქვენი ბალანსი შეივსო!',
    backToHome: 'მთავარზე დაბრუნება',
    emailLabel: 'ელ-ფოსტა',
    loginTitle: 'შესვლა',
    registerTitle: 'ანგარიშის შექმნა',
    authSubtitle: 'დაიწყეთ უფასო AI ვიდეოების შექმნა',
    freeTrialBadge: 'შექმენით 3 უფასო ვიდეო',
    nameLabel: 'სახელი',
    passwordLabel: 'პაროლი',
    confirmPasswordLabel: 'დაადასტურეთ პაროლი',
    signInBtn: 'შესვლა',
    signUpBtn: 'ანგარიშის შექმნა',
    haveAccount: 'უკვე გაქვთ ანგარიში?',
    noAccount: 'არ გაქვთ ანგარიში?',
    profileTitle: 'პროფილი',
    currentPlan: 'მიმდინარე გეგმა',
    usageStats: 'სტატისტიკა',
    imagesGenerated: 'შექმნილი სურათები',
    videosGenerated: 'შექმნილი ვიდეოები',
    logout: 'გასვლა',
    navLogin: 'შესვლა',
    navProfile: 'პროფილი',
    welcomeBack: 'მოგესალმებით',
    viewAll: 'ყველას ნახვა',
    termsText: 'ვეთანხმები გამოყენების პირობებს',
    privacyText: 'ვეთანხმები კონფიდენციალურობის პოლიტიკას',
    authFeatureInstant: 'მყისიერი გენერაცია',
    authFeatureHD: 'HD ხარისხი',
    authFeatureSecure: 'უსაფრთხო და სანდო',
    usageLimitReached: 'ლიმიტი ამოწურულია',
    usageUpgradeMsg: 'განაახლეთ გეგმა გასაგრძელებლად.',
    usageRemaining: 'დარჩენილი',
    upgradePlan: 'გეგმის განახლება',
    tabOverview: 'მიმოხილვა',
    tabHistory: 'ისტორია',
    tabSettings: 'პარამეტრები',
    noHistory: 'კონტენტი ჯერ არ შექმნილა.',
    saveChanges: 'შენახვა',
    settingsSaved: 'მონაცემები განახლდა!',
    showMore: 'მეტის ნახვა',
    showLess: 'ნაკლების ნახვა',
    magicToolTitle: 'AI კრეატიული სტუდია',
    magicToolDesc: 'გენერაციული ხელსაწყოები და სწრაფი მოქმედებები თქვენი იდეების განსახორციელებლად.',
    genTextToImage: 'ტექსტი სურათად',
    genFill: 'გენერაციული შევსება',
    genImageFromScene: 'სცენა სურათად',
    genTextToVector: 'ტექსტი ვექტორად',
    genRecolor: 'გადაღებვა',
    genTextEffects: 'ტექსტური ეფექტები',
    genTemplate: 'შაბლონის შექმნა',
    genTextToVideo: 'ტექსტი ვიდეოდ',
    genImageToVideo: 'სურათი ვიდეოდ',
    genMusic: 'მუსიკის შექმნა',
    genSoundFx: 'ხმის ეფექტები',
    genAvatar: 'ტექსტი ავატარად',
    genTextToSpeech: 'ტექსტი მეტყველებად',
    genVoiceToSfx: 'ხმა SFX-ად',
    genLogo: 'ლოგოს შექმნა',
    qaTitle: 'სწრაფი მოქმედებები',
    qaRemoveBg: 'ფონის წაშლა',
    qaCropImage: 'სურათის მოჭრა',
    qaMergeVideo: 'ვიდეოს გაერთიანება',
    qaSubtitle: 'სუბტიტრების დამატება',
    qaQrCode: 'QR კოდი',
    qaCropVideo: 'ვიდეოს მოჭრა',
    qaResizeVideo: 'ვიდეოს ზომის შეცვლა',
    qaTrimVideo: 'ვიდეოს დამოკლება',
    qaConvertMp4: 'MP4-ში კონვერტაცია',
    qaResizeImage: 'სურათის ზომის შეცვლა',
    qaTranslateVideo: 'ვიდეოს თარგმნა',
    qaEnhanceSpeech: 'საუბრის გაუმჯობესება',
    qaTranslateAudio: 'აუდიოს თარგმნა',
    navVideoTools: 'ვიდეო ხელსაწყოები',
    navImageTools: 'ფოტო ხელსაწყოები',
    navAudioTools: 'აუდიო ხელსაწყოები',
    enterAmount: 'შეიყვანეთ თანხა (AZN)',
    creditsReceived: 'მისაღები კრედიტები',
    topUpBtn: 'ბალანსის შევსება',
    quickPayTitle: 'სწრაფი გადახდა',
    betaDisclaimer: 'ყურადღება: ეს არის ბეტა ვერსია, შესაძლოა დაფიქსირდეს ხარვეზები. ბოდიშს გიხდით შეფერხებისთვის. პატივისცემით, Sehirbaz AI.'
  }
};